#include "bme280.h"
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"
#include "sdkconfig.h"  // generated by "make menuconfig"

#define SDA_PIN 23
#define SCL_PIN 22

#define TAG_BME280 "BME280"

#define I2C_MASTER_ACK 0
#define I2C_MASTER_NACK 1

// ------------------

#define SUCCESS ((uint8_t)0)
#define BME280_INIT_VALUE (0)
#define BME280_I2C_ADDRESS

// -------------------------------

void i2c_master_init() {
  i2c_config_t i2c_config = {.mode = I2C_MODE_MASTER,
                             .sda_io_num = SDA_PIN,
                             .scl_io_num = SCL_PIN,
                             .sda_pullup_en = GPIO_PULLUP_ENABLE,
                             .scl_pullup_en = GPIO_PULLUP_ENABLE,
                             .master.clk_speed = 1000000};

  i2c_param_config(I2C_NUM_0, &i2c_config);
  i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

int8_t BME280_I2C_bus_write(u_int8_t dev_addr, u_int8_t reg_addr, u_int8_t *reg_data, u_int8_t cnt) {
  int32_t iError = BME280_INIT_VALUE;

  esp_err_t espRc;
  i2c_cmd_handle_t cmd = i2c_cmd_link_create();

  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);

  i2c_master_write_byte(cmd, reg_addr, true);
  i2c_master_write(cmd, reg_data, cnt, true);
  i2c_master_stop(cmd);

  espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
  if (espRc == ESP_OK) {
    iError = SUCCESS;
  } else {
    iError = FAIL;
  }
  i2c_cmd_link_delete(cmd);

  return (int8_t)iError;
}

int8_t BME280_I2C_bus_read(u_int8_t dev_addr, u_int8_t reg_addr, u_int8_t *reg_data, u_int8_t cnt) {
  int32_t iError = BME280_INIT_VALUE;
  esp_err_t espRc;

  i2c_cmd_handle_t cmd = i2c_cmd_link_create();

  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);
  i2c_master_write_byte(cmd, reg_addr, true);

  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_READ, true);

  if (cnt > 1) {
    i2c_master_read(cmd, reg_data, cnt - 1, I2C_MASTER_ACK);
  }
  i2c_master_read_byte(cmd, reg_data + cnt - 1, I2C_MASTER_NACK);
  i2c_master_stop(cmd);

  espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
  if (espRc == ESP_OK) {
    iError = SUCCESS;
  } else {
    iError = FAIL;
  }

  i2c_cmd_link_delete(cmd);

  return (int8_t)iError;
}

void BME280_delay_msek(u_int32_t msek) { vTaskDelay(msek / portTICK_PERIOD_MS); }

void task_bme280_normal_mode(void *ignore) {
  struct bme280_dev bme280 = {// /*! Chip Id */
                              .chip_id = BME280_CHIP_ID,

                              // /*! Device Id */
                              .dev_id = BME280_I2C_ADDR_SEC,

                              // /*! SPI/I2C interface */
                              .intf = BME280_I2C_INTF,

                              // /*! Read function pointer */
                              .read = BME280_I2C_bus_read,

                              // /*! Write function pointer */
                              .write = BME280_I2C_bus_write,

                              // /*! Delay function pointer */
                              .delay_ms = BME280_delay_msek,

                              // /*! Trim data */
                              // struct bme280_calib_data calib_data;

                              // /*! Sensor settings */
                              .settings = {.osr_p = BME280_OVERSAMPLING_16X,
                                           .osr_t = BME280_OVERSAMPLING_2X,
                                           .osr_h = BME280_OVERSAMPLING_1X,
                                           .filter = BME280_FILTER_COEFF_16,
                                           .standby_time = BME280_STANDBY_TIME_0_5_MS}};

  int8_t result;

  result = bme280_init(&bme280);
  if (result == BME280_OK) {
    ESP_LOGI(TAG_BME280, "Successfully initialized BME280!");
  } else if (result > 0) {
    ESP_LOGW(TAG_BME280, "BME280 initialization warning: %d", result);
  } else {
    switch (result) {
      case BME280_E_NULL_PTR:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: NULL_PTR (%d)", result);
        break;
      case BME280_E_DEV_NOT_FOUND:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: BME280_E_DEV_NOT_FOUND (%d)", result);
        break;
      case BME280_E_INVALID_LEN:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: BME280_E_INVALID_LEN (%d)", result);
        break;
      case BME280_E_COMM_FAIL:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: BME280_E_COMM_FAIL (%d)", result);
        break;
      case BME280_E_SLEEP_MODE_FAIL:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: BME280_E_SLEEP_MODE_FAIL (%d)", result);
        break;
      case BME280_E_NVM_COPY_FAILED:
        ESP_LOGE(TAG_BME280, "BME280 initialization error: NVM_COPY_FAILED (%d)", result);
        break;
    }
    return;
  }

  result = bme280_set_sensor_mode(BME280_NORMAL_MODE, &bme280);
  if (result == BME280_OK) {
    ESP_LOGI(TAG_BME280, "Successfully set sensor mode to 'normal'");
  } else {
    ESP_LOGE(TAG_BME280, "Unsuccessful setting sensor mode. Result: %d", result);
    return;
  }

  while (true) {
    vTaskDelay(100 / portTICK_PERIOD_MS);

    struct bme280_data data;
    result = bme280_get_sensor_data(BME280_ALL, &data, &bme280);
    if (result == BME280_OK) {
      ESP_LOGI(TAG_BME280, "%.2f degC / %.3f hPa / %.3f %%", data.temperature,
               data.pressure / 100,  // Pa -> hPa
               data.humidity);
    } else if (result > 0) {
      ESP_LOGW(TAG_BME280, "BME280 get sensor data warning: %d", result);
    } else {
      ESP_LOGE(TAG_BME280, "BME280 got sensor data error: %d", result);
    }
  }

  vTaskDelete(NULL);
}

void app_main(void) {
  i2c_master_init();
  xTaskCreate(&task_bme280_normal_mode, "bme280_normal_mode", 2048, NULL, 6, NULL);
}
